### ISSUE TITLE
Seems to be causing already loaded images to flash

### ISSUE THREAD

**Issue by acomito** [DeedMob/react-load-image#1]
Thanks for updating the old repo. I'm building an infinite scroll list similar to instagram, and having some trouble with image loading time. I figured I'd give this a try. It works as expected generally, but there is some flashing of already loaded images sometimes. I'm not sure if there's a re-render being caused somewhere or what.

I'll try to get a reproduction together, or at least a gif.

**Comment by davidfurlong** [comment]
Reopen if you see this again/have a repro!
