### ISSUE TITLE
Snapshot testing support

### ISSUE THREAD

**Issue by Paveltarno** [DeedMob/react-load-image#8]
While attempting to snapshot test `react-load-image` an error will be thrown as the `Image` object invokes `handleLoad` before finishing initialization, thus cleaning itself up before the process is done.  This will result in `this.img` being `undefined` and setting `srcset` will result in an error

**Comment by davidfurlong** [comment]
Apologies, I didn't see the notifications of this despite watching the repo.

**Comment by davidfurlong** [comment]
Released in 0.1.7
